entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  duckdns:
    acme:
      email: "your-email@example.com"  # Replace
      storage: "/acme.json"
      dnsChallenge:
        provider: duckdns
        delayBeforeCheck: 0
